export default class AppService {
    searchAPP = filter => {
        /*return Promise.resolve(
            [
                {
                "state": "LIMA",
                "province": "LIMA",
                "district": "LIMA",
                "type": "Charla en colegio",
                "startDate": "2019-02-01",
                "stateCode": 15,
                "provinceCode": 1501,
                "districtCode": 150101,
                "area": 1,
                "actionCode": "A-1002",
                "campaign": 8,
                "ojM": 0,
                "ojV": 0,
                "opM": 0,
                "opV": 0,
                "osM": 0,
                "osV": 0,
                "aufrM": 0,
                "aufrV": 0,
                "auflM": 0,
                "auflV": 0,
                "aucM": 0,
                "aucV": 0,
                "edM": 0,
                "edV": 0,
                "esM": 0,
                "esV": 0,
                "esuM": 0,
                "esuV": 0,
                "paM": 0,
                "paV": 0,
                "licoM": 0,
                "licoV": 0,
                "faM": 0,
                "faV": 0,
                "proM": 0,
                "proV": 0,
                "colM": 0,
                "colV": 0,
                "sereM": 0,
                "sereV": 0,
                "fupuM": 0,
                "fupuV": 0,
                "fupriM": 0,
                "fupriV": 0,
                "empM": 0,
                "empV": 0,
                "gempM": 0,
                "gempV": 0,
                "trabM": 0,
                "trabV": 0,
                "contM": 0,
                "contV": 0,
                "perM": 0,
                "perV": 0,
                "osbM": 0,
                "osbV": 0,
                "mrcM": 0,
                "mrcV": 0,
                "rongM": 0,
                "rongV": 0,
                "mmcrM": 0,
                "mmcrV": 0,
                "acM": 0,
                "acV": 0,
                "poM": 0,
                "poV": 0,
                "otM": 0,
                "otV": 0,
                "infM": 0,
                "infV": 0,
                "ninM": 0,
                "ninV": 0,
                "adoM": 0,
                "adoV": 0,
                "adoTM": 0,
                "adoTV": 0,
                "jovM": 0,
                "jovV": 0,
                "aduM": 0,
                "aduV": 0,
                "mayM": 0,
                "mayV": 0,
                "cemcode": "LIMA"
                },
                {
                    "state": "LIMA",
                "province": "LIMA",
                "district": "LIMA",
                "type": "Charla en colegio",
                    "startDate": "2019-02-01",
                    "stateCode": 15,
                    "provinceCode": 1501,
                    "districtCode": 150101,
                    "area": 1,
                    "actionCode": "A-1002",
                    "campaign": 8,
                    "ojM": 0,
                    "ojV": 0,
                    "opM": 0,
                    "opV": 0,
                    "osM": 0,
                    "osV": 0,
                    "aufrM": 0,
                    "aufrV": 0,
                    "auflM": 0,
                    "auflV": 0,
                    "aucM": 0,
                    "aucV": 0,
                    "edM": 0,
                    "edV": 0,
                    "esM": 0,
                    "esV": 0,
                    "esuM": 0,
                    "esuV": 0,
                    "paM": 0,
                    "paV": 0,
                    "licoM": 0,
                    "licoV": 0,
                    "faM": 0,
                    "faV": 0,
                    "proM": 0,
                    "proV": 0,
                    "colM": 0,
                    "colV": 0,
                    "sereM": 0,
                    "sereV": 0,
                    "fupuM": 0,
                    "fupuV": 0,
                    "fupriM": 0,
                    "fupriV": 0,
                    "empM": 0,
                    "empV": 0,
                    "gempM": 0,
                    "gempV": 0,
                    "trabM": 0,
                    "trabV": 0,
                    "contM": 0,
                    "contV": 0,
                    "perM": 0,
                    "perV": 0,
                    "osbM": 0,
                    "osbV": 0,
                    "mrcM": 0,
                    "mrcV": 0,
                    "rongM": 0,
                    "rongV": 0,
                    "mmcrM": 0,
                    "mmcrV": 0,
                    "acM": 0,
                    "acV": 0,
                    "poM": 0,
                    "poV": 0,
                    "otM": 0,
                    "otV": 0,
                    "infM": 0,
                    "infV": 0,
                    "ninM": 0,
                    "ninV": 0,
                    "adoM": 0,
                    "adoV": 0,
                    "adoTM": 0,
                    "adoTV": 0,
                    "jovM": 0,
                    "jovV": 0,
                    "aduM": 0,
                    "aduV": 0,
                    "mayM": 0,
                    "mayV": 0,
                    "cemcode": "LIMA"
                    },
            ]
        ); */
        const url = `http://localhost:8080/impact/app?startDate=${filter.startDate}&endDate=${filter.endDate}&state=${filter.state}&province=${filter.province}&district=${filter.district}`;
        return fetch(url).then(response => response.json());
    }
/*
    example = filter => {
        const url = `url/traer-algo`;
        return fetch(url).then(response => response.json());
    }}*/
}