export const clusteringAlgorithmsNames = {
    '0' : 'K-Medoids',
    '1' : 'DBSCAN',
    '2' : 'Linkage',
};

export const algorithmDescription = {
    '0' : 'K-Medoids es un método de agrupamiento particional, lo que significa que inicia partiendo el conjunto total de casos en "K" grupos al azar, y va reagrupando los casos de tal forma que dentro de cada grupo los casos tengan la mayor similitud posible entre sí.\nEsto lo hace escogiendo "K" casos al azar que representan los "K" grupos iniciales, luego se le asocia a cada grupo los demás casos sin grupo. Una vez hecho esto se busca para cada grupo el elemento que más se parece con el resto del grupo para convertirlos en los nuevos representantes de cada grupo. Luego, se vuelve a agrupar todos los casos pero esta vez tomando como referencia a los nuevos representantes de cada grupo y el ciclo se repite hasta que los representantes de cada grupo sean los más parecidos con el resto del grupo y no se asignen nuevos representantes.',
    '1' : `DBSCAN es un método de agrupamiento que usa dos parámetros: un NÚMERO DE VECINOS y el valor EPS que hace referencia a qué tan diferentes pueden ser dos casos entre sí para ser considerados vecinos.\nUn elemento tendrá más vecinos a medida que el EPS sea mayor, este parámetro puede tener valores entre 0.10 y 0.80.\nEn este método existen:\n\n<> Elementos núcleo: son aquellos que tienen al menos el número de vecinos que se ha especificado en la parte superior.\n\n<> Elementos contorno: son aquellos que no tienen el número suficiente de vecinos para ser un elemento núcleo pero que tienen como vecino a por lo menos un elemento núcleo.\n\n<> Elementos extraños: son aquellos que no son elementos núcleo ni tienen como vecino a algún elemento núcleo.\n\nLos grupos en este caso se arman primero tomando en cuenta a todos los elementos núcleo que sean vecinos entre sí, luego se añade a los elementos contorno a cada grupo al que sean más cercanos, y los elementos extraños son dejados de lado.`,
    '2' : 'Linkage es un método de agrupamiento de tipo jerárquico aglomerativo y que forma los grupos partiendo de la base que cada elemento es un grupo de un elemento.\nLuego, va "aglomerando" estos grupos en base a qué tan "cerca" se encuentra un grupo del otro. Debido a que se está usando el método Linkage Promedio, la cercanía entre grupos se define como la similitud o distancia promedio entre cada elemento de un grupo con cada elemento del otro grupo.\nFinalmente, el método aglomerará grupos entre sí hasta que el número restante de grupos sea el que se defina en la parte superior.',
}